default:
  theme_modern_toolbar_align: left
  theme_modern_buttons3_add:
    - tablecontrols
    - fullscreen
    - media
  plugins:
    - table
    - fullscreen
    - media

alternate:
  theme_modern_toolbar_location: top
  theme_modern_toolbar_align: left
  theme_modern_buttons3_add:
    - tablecontrols
  plugins:
    - table